### ISSUE TITLE
I  found sql injection vulnerability

### ISSUE THREAD

**Issue by Sharyie** [RAOE/show-videos#11]
hello,I am a cyber security amateur and found 6 vulnerabilitys using codeql script in this project.here is detail:
scetc-show-videos-admin project,com.show.admin.scetc.controller.BgmController:53
```
	@RequestMapping("/selectBgmList")
	public XyfJsonResult selectBgmList(String keyword, String title,
			@RequestParam(value = "page", required = true, defaultValue = "1") Integer page,
			@RequestParam(value = "pageSize", required = true, defaultValue = "10") Integer pageSize) {
		PageResult list = bgmService.queryAll(page, pageSize, keyword, title);
		return XyfJsonResult.ok(list);
	}
```
parameter keyword and title is from user input and could contains evil code.then value passed to bgmService.queryAll function,lets goto:
```
	public PageResult queryAll(Integer page, Integer pageSize, String keyword, String title) {

		PageHelper.startPage(page, pageSize);
		List<Bgm> list = bgmMapper.queryAll(keyword, title);
		// 3、获取分页查询后的数据
		PageInfo<Bgm> pageInfo = new PageInfo<>(list);
		// 4、封装需要返回的分页实体
		PageResult result = new PageResult();
		// 设置获取到的总记录数total：
		result.setTotal(pageInfo.getPages());
		// 设置数据集合rows：
		result.setRows(list);
		result.setRecords(pageInfo.getTotal());
		result.setPage(page);
		return result;
	}
```
keyword and title transfered to bgmMapper.queryAll function.lets goto:
```
	List<Bgm> queryAll(@Param("keyword") String keyword, @Param("title") String title);
```
this is a mapper interface of mybatis.according to mapper.xml, it will execute sql statement in src/main/resources/mapper/BgmMapper.xml:
```
<mapper namespace="com.show.admin.scetc.mapper.BgmMapper">

	<select id="queryAll" resultType="Bgm" parameterType="String">
		select * from bgm
		where 1=1
		<if test="keyword != null and keyword !=''">
			and name like '%${keyword}%'
		</if>
		<if test="title != null and title !=''">
			or author like '%${title}%'
		</if>
	</select>
```
well,value of keyword and title will joint to sql statement.hacker could pass extra sql code to do something evil.like this:
```
http://x.x.x.x/bgm/selectBgmList?keyword=a' and 1=2 union select null,null,user(),null--+
```
this http request will cause extra sql execution of "select null,null,user(),null", hacker will get the user of current db.otherwise,hacker could delete database or add users.it's every dangerous.

other 4 vulns is the same.I will point the entrance and sql injection param:
scetc-show-videos-admin:com.show.admin.scetc.controller.VideoController:60, queryAll function,keyword and title params
scetc-show-videos-admin:com.show.admin.scetc.controller.VideoController:42, selectVideoType function,keyword param
scetc-show-videos-dev/scetc-show-videos-mini-api:src/main/java/com/show/controller/VideoController.java:258,showAll function.videoDesc param.

now,the question is How to fix this vuln? modify sql statement like this is ok:
```
<if test="keyword != null and keyword !=''">
			and name like concat('%',#{keyword},'%')
		</if>
		<if test="title != null and title !=''">
			or author like concat('%',#{title},'%')
		</if>
```
finally,this is a good project.I really love it,hope for you patch.

以下是中文描述：
您好，我是一个网络安全爱好者，我用 Codeql 工具和我自己写的 mybatis SQL 注入脚本检测到您的工程中存在 SQL 注入漏洞。详细说明如下：
在 scetc-show-videos-admin 工程 com.show.admin.scetc.controller.BgmController:53
```
	@RequestMapping("/selectBgmList")
	public XyfJsonResult selectBgmList(String keyword, String title,
			@RequestParam(value = "page", required = true, defaultValue = "1") Integer page,
			@RequestParam(value = "pageSize", required = true, defaultValue = "10") Integer pageSize) {
		PageResult list = bgmService.queryAll(page, pageSize, keyword, title);
		return XyfJsonResult.ok(list);
	}
```
参数 keyword 和 title 是来自用户输入的，用户可以输入任意值，可能包含恶意代码，这两个参数的值会传递到 bgmService.queryAll 方法，跟进该方法：
```
	public PageResult queryAll(Integer page, Integer pageSize, String keyword, String title) {

		PageHelper.startPage(page, pageSize);
		List<Bgm> list = bgmMapper.queryAll(keyword, title);
		// 3、获取分页查询后的数据
		PageInfo<Bgm> pageInfo = new PageInfo<>(list);
		// 4、封装需要返回的分页实体
		PageResult result = new PageResult();
		// 设置获取到的总记录数total：
		result.setTotal(pageInfo.getPages());
		// 设置数据集合rows：
		result.setRows(list);
		result.setRecords(pageInfo.getTotal());
		result.setPage(page);
		return result;
	}
```
keyword 和 title 的值传递到了 bgmMapper.queryAll 方法中，跟进该方法：
```
	List<Bgm> queryAll(@Param("keyword") String keyword, @Param("title") String title);
```
这是一个 mybatis 的接口，该方法会去执行 SQL 语句，SQL 语句就在 src/main/resources/mapper/BgmMapper.xml:
```
<mapper namespace="com.show.admin.scetc.mapper.BgmMapper">

	<select id="queryAll" resultType="Bgm" parameterType="String">
		select * from bgm
		where 1=1
		<if test="keyword != null and keyword !=''">
			and name like '%${keyword}%'
		</if>
		<if test="title != null and title !=''">
			or author like '%${title}%'
		</if>
	</select>
```
可以看到的，用户输入的 keyword 和 title 通过 ${keyword} 和 ${title} 拼接到了 SQL 语句中，黑客就可以通过如下的请求让服务端执行额外的 SQL 语句：
```
http://x.x.x.x/bgm/selectBgmList?keyword=a' and 1=2 union select null,null,user(),null--+
```
该 http 请求会导致 select null,null,user(),null 语句的执行，那么攻击者就可以知道数据库的当前用户，当然还可以执行其他查询，比如删除数据库，添加用户等，这非常危险。
上面描述了两个注入点，剩下的 4 个注入点是类似的，我会给出攻击入口和注入参数：
scetc-show-videos-admin:com.show.admin.scetc.controller.VideoController:60, queryAll 方法,keyword 和 title 参数
scetc-show-videos-admin:com.show.admin.scetc.controller.VideoController:42, selectVideoType 方法,keyword 参数
scetc-show-videos-dev/scetc-show-videos-mini-api:src/main/java/com/show/controller/VideoController.java:258,showAll 方法.videoDesc 参数.

那么，该怎么修复这个漏洞呢？按照下面的方式修改 SQL 语句就可以了：
```
<if test="keyword != null and keyword !=''">
			and name like concat('%',#{keyword},'%')
		</if>
		<if test="title != null and title !=''">
			or author like concat('%',#{title},'%')
		</if>
```
最后，这是一个不错的项目，我真的喜欢它，期望您可以修复。

**Comment by RAOE** [comment]
您好，SQL注入相关的问题已经按照你的建议解决，感谢你的贡献
https://github.com/RAOE/show-videos/pull/12
