### ISSUE TITLE
关于图片视频上传问题

### ISSUE THREAD

**Issue by LOUSANPANG** [RAOE/show-videos#2]
**问题描述**
* 上传图片、视频过大

**问题请教**
* 在上传图片、视频前进行压缩等优化

**开发信息**
>  `Taro v1.3.17`  - > 微信小程序

**Comment by RAOE** [comment]
感谢你的建议，作为短视频项目 没有需要上传太大的视频的需求。 加上服务器带宽有限。在视频上传优化方便之后会进行修改。

**Comment by gocpplua** [comment]
> 作为短视频项目 没有需要上传太大的视频的需求。 加上服务器带宽有限。在视频

视频上传是怎么实现的，后台存储在哪？
